#!/usr/bin/env bash
# Regenerates apps/web/src/lib/contracts/{abis.ts,addresses.ts} from the
# compiled artifacts and contracts/deployments/*.json.
# Run from contracts/: scripts/export-web.sh [anvil|sepolia]
set -euo pipefail

cd "$(dirname "$0")/.."
CHAIN="${1:-anvil}"
OUT="../apps/web/src/lib/contracts"
mkdir -p deployments

{
  echo '// GENERATED by contracts/scripts/export-web.sh — do not edit by hand.'
  echo ''
  for pair in MockUSDC:mockUsdc HumanRegistry:humanRegistry RareItems:rareItems RareMarket:rareMarket RoosterRWA:roosterRwa; do
    c=${pair%%:*}
    n=${pair##*:}
    abi=$(forge inspect "$c" abi --json 2>/dev/null | jq -c .) || continue # contract not written yet
    [ "$abi" = "null" ] && continue
    echo "export const ${n}Abi = $abi as const;"
    echo ''
  done
} > "$OUT/abis.ts"

{
  echo '// GENERATED by contracts/scripts/export-web.sh — do not edit by hand.'
  echo '// Values come from contracts/deployments/<chain>.json.'
  echo 'export type ChainAddresses = {'
  echo '  HumanRegistry: `0x${string}`;'
  echo '  RareItems: `0x${string}`;'
  echo '  RareMarket: `0x${string}`;'
  echo '  MockUSDC: `0x${string}`;'
  echo '  RoosterRWA: `0x${string}`;'
  echo '};'
  echo ''
  echo 'export const ADDRESSES: Record<number, ChainAddresses> = {'
  for f in deployments/*.json; do
    name=$(basename "$f" .json)
    id=$(jq -r '.chainId' "$f")
    echo "  $id: {"
    for k in HumanRegistry RareItems RareMarket MockUSDC RoosterRWA; do
      echo "    $k: \"$(jq -r ".\"$k\"" "$f")\","
    done
    echo "  }, // $name"
  done
  echo '};'
  echo ''
  echo 'export function getAddresses(chainId: number): ChainAddresses {'
  echo '  const a = ADDRESSES[chainId];'
  echo '  if (!a) throw new Error(`No deployed contracts for chain ${chainId}`);'
  echo '  return a;'
  echo '}'
} > "$OUT/addresses.ts"

echo "Wrote $OUT/abis.ts and $OUT/addresses.ts"
