// GENERATED by contracts/scripts/export-web.sh — do not edit by hand.
// Values come from contracts/deployments/<chain>.json.
export type ChainAddresses = {
  HumanRegistry: `0x${string}`;
  RareItems: `0x${string}`;
  RareMarket: `0x${string}`;
  MockUSDC: `0x${string}`;
};

export const ADDRESSES: Record<number, ChainAddresses> = {
  31337: {
    HumanRegistry: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    RareItems: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    RareMarket: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    MockUSDC: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  }, // anvil
};

export function getAddresses(chainId: number): ChainAddresses {
  const a = ADDRESSES[chainId];
  if (!a) throw new Error(`No deployed contracts for chain ${chainId}`);
  return a;
}
