// GENERATED by contracts/scripts/export-web.sh — do not edit by hand.
// Values come from contracts/deployments/<chain>.json.
export type ChainAddresses = {
  HumanRegistry: `0x${string}`;
  RareItems: `0x${string}`;
  RareMarket: `0x${string}`;
  MockUSDC: `0x${string}`;
  RoosterRWA: `0x${string}`;
};

export const ADDRESSES: Record<number, ChainAddresses> = {
  31337: {
    HumanRegistry: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    RareItems: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
    RareMarket: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
    MockUSDC: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
    RoosterRWA: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
  }, // anvil
};

export function getAddresses(chainId: number): ChainAddresses {
  const a = ADDRESSES[chainId];
  if (!a) throw new Error(`No deployed contracts for chain ${chainId}`);
  return a;
}
