// GENERATED by contracts/scripts/export-web.sh — do not edit by hand.
// Values come from contracts/deployments/<chain>.json.
export type ChainAddresses = {
  HumanRegistry: `0x${string}`;
  RareItems: `0x${string}`;
  RareMarket: `0x${string}`;
  MockUSDC: `0x${string}`;
  RoosterRWA: `0x${string}`;
};

export const ADDRESSES: Record<number, ChainAddresses> = {
  31337: {
    HumanRegistry: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
    RareItems: "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
    RareMarket: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
    MockUSDC: "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
    RoosterRWA: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
  }, // anvil
};

export function getAddresses(chainId: number): ChainAddresses {
  const a = ADDRESSES[chainId];
  if (!a) throw new Error(`No deployed contracts for chain ${chainId}`);
  return a;
}
